name: anytime
description: Anytime Podcast Player

version: 0.1.3+22

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  audio_service: ^0.16.1
  audio_session: ^0.0.11
  cached_network_image: ^2.5.0
  connectivity: ^0.4.8+6
  flutter_dialogs: ^1.0.3
  flutter_downloader: ^1.5.2
  flutter_launcher_icons: ^0.7.4
  flutter_spinkit: ^4.1.2+1
  html: ^0.14.0+3
  just_audio: ^0.2.2
  liquid_pull_to_refresh: ^2.0.0
  logging: ^0.11.4
  mockito: ^4.1.3
  mp3_info: ^0.1.4
  package_info: ^0.4.0+18
  path_provider: ^1.6.10
  percent_indicator: ^2.1.9
  permission_handler: ^5.0.0+hotfix.6
  podcast_search: ^0.3.8
  provider: ^4.1.2
  rxdart: ^0.24.1
  sembast: ^2.4.8+1
  shared_preferences: ^0.5.8
  url_launcher: ^5.4.7

  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.16.0
  intl_translation:

  cupertino_icons: ^0.1.2

dev_dependencies:
  pedantic: ^1.9.2
  flutter_test:
    sdk: flutter

flutter_icons:
  image_path: "assets/images/anytime-logo.png"
  android: true
  ios: true

flutter:

  uses-material-design: true

  assets:
    - assets/images/anytime-logo.png
    - assets/images/anytime-logo-s.png

  fonts:
    - family: IBMPlexSans
      fonts:
        - asset: assets/fonts/IBMPlexSans-Thin.otf
          weight: 100
        - asset: assets/fonts/IBMPlexSans-ThinItalic.otf
          weight: 100
          style: italic
        - asset: assets/fonts/IBMPlexSans-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/IBMPlexSans-ExtraLightItalic.otf
          weight: 200
          style: italic
        - asset: assets/fonts/IBMPlexSans-Light.otf
          weight: 300
        - asset: assets/fonts/IBMPlexSans-LightItalic.otf
          weight: 300
          style: italic
        - asset: assets/fonts/IBMPlexSans-Regular.otf
          weight: 400
        - asset: assets/fonts/IBMPlexSans-Italic.otf
          weight: 400
          style: italic
        - asset: assets/fonts/IBMPlexSans-Medium.otf
          weight: 500
        - asset: assets/fonts/IBMPlexSans-MediumItalic.otf
          weight: 500
          style: italic
        - asset: assets/fonts/IBMPlexSans-SemiBold.otf
          weight: 600
        - asset: assets/fonts/IBMPlexSans-SemiBoldItalic.otf
          weight: 600
          style: italic
        - asset: assets/fonts/IBMPlexSans-Bold.otf
          weight: 700
        - asset: assets/fonts/IBMPlexSans-BoldItalic.otf
          weight: 700
          style: italic
    - family: SpaceMonoRegular
      fonts:
        - asset: assets/fonts/SpaceMono-Regular.ttf
    - family: SpaceMonoBold
      fonts:
        - asset: assets/fonts/SpaceMono-Bold.ttf
    - family: RobotoCondensedBold
      fonts:
        - asset: assets/fonts/RobotoCondensed-Bold.ttf
    - family: RobotoRegular
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
    - family: MontserratMedium
      fonts:
        - asset: assets/fonts/Montserrat-Medium.otf
    - family: MontserratRegular
      fonts:
        - asset: assets/fonts/Montserrat-Regular.otf
    - family: MontserratBold
      fonts:
        - asset: assets/fonts/Montserrat-Bold.otf
    - family: JostRegular
      fonts:
        - asset: assets/fonts/jost/Jost-Regular.ttf
